# Site
name: 'Vernacular.ai Tech'
description: 'Speech Technology from Vernacular.ai'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-katex

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

authors:
    anirudhdagar:
      name:           Anirudh Dagar
      # site:         https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            ""
      twitter:        https://github.com/anirudhdagar
    kritianandan:
      name:           Kriti Anandan
      # site:         https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            ""
      twitter:        https://github.com/kritianandan98
    swarajdalmia:
      name:           Swaraj Dalmia
      # site:         https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            ""
      twitter:        https://github.com/swarajdalmia
    janaab11:
      name:           Kumar Manas
      # site:         https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            ""
      twitter:        https://github.com/janaab11/
    lepisma:
      name:           Abhinav Tushar
      # site:         https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            ""
      twitter:        https://lepisma.xyz/

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
