name: "Vernacular.ai Tech"
description: "Speech Technology from Vernacular.ai"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""

include: ["_pages"]
permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post

  - scope:
      path: "_pages"
    values:
      layout: page

markdown: kramdown
highlighter: rouge
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [Gemfile, Gemfile.lock, node_modules, .jekyll-cache, .sass-cache]
